ln -fs ~/dot-files/stumpwmrc ~/.stumpwmrc
ln -fs ~/dot-files/xinitrc ~/.xinitrc
ln -fs ~/dot-files/xmodmaprc ~/.xmodmaprc
ln -fs ~/dot-files/Xresources ~/.Xresources
ln -fs ~/dot-files/tmux.conf ~/.tmux.conf
ln -fs ~/dot-files/acoc.conf ~/.acoc.conf
ln -fs ~/dot-files/conkerorrc ~/.conkerorrc
ln -fs ~/dot-files/gitconfig ~/.gitconfig
ln -fs ~/dot-files/zsh/ ~/.zsh
ln -fs ~/dot-files/zshrc ~/.zshrc
